version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 wsgi:app
    environment:
      - DATABASE_URL=postgresql://flask_docker_db_user:mEaADj4DREgfAxoSZUqhHf89Xg0U2Kaz@dpg-d20fbevgi27c73ciacug-a.singapore-postgres.render.com/flask_docker_db
      - JWT_SECRET_KEY=super-secret
    ports:
      - "5090:5000"
    depends_on:
      - db

volumes:
  postgres_data: